### ISSUE TITLE
[High prior ]Helloword for idrice project

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/idrice-app#45]
You have to update your method to work: TAKE THIS AS EXAMPLE 
@idrice24  
The picture explains  what i m talking about..
1. Helloworld sample
1. Just 2 functions ( see 1, 2 red)
1. Site address is set properly --> no github domain
1.  Dummy message is set properly
1.  Function to store email 

https://www.hi-techn.com/password

Idrice web site should done the same-- 

![image](https://user-images.githubusercontent.com/13945825/94261037-7df65f00-ff31-11ea-9aa3-8c78dca164b0.png)

**Comment by idrice24** [comment]
I am not understanding what you are asking me to do
I have already passed the step of helloword

**Comment by Ghislain1** [comment]
Your Website address is wrong!!

**Comment by Ghislain1** [comment]
See 1 on the picture --> this is legacy web address

**Comment by idrice24** [comment]
i am still thinking for a good one
