### ISSUE TITLE
[Helloworld Bug]  Remove shared component

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/idrice-app#46]
@idrice24 
refactory the code as soon as possible:
1. from you archictecture shared is not a component --> share is a module --> do you understand what module is?
1. Navbar is not a part of shared-module --> remove it
1. Navigation part should be removed
1. example should be removed

**Comment by idrice24** [comment]
Why should I removed navigation part and example?

**Comment by Ghislain1** [comment]
this is not a part of helloworld.. we work step by step

**Comment by Ghislain1** [comment]
Look at https://www.hi-techn.com/  -- That guy just have   Opening Soon page !! -->

**Comment by idrice24** [comment]
yes but i am trying to go forward with it
